# --- ENVIRONMENT

FROM node:18.13.0 AS production

WORKDIR /usr/src/api

RUN npm install -g @nestjs/cli

COPY ./api/package*.json ./ 
COPY ./envs/.security.env ./api
COPY ./envs/.production.env ./.env

RUN npm i --omit=dev --ignore-scripts

RUN npm uninstall bcrypt && npm install bcrypt

COPY ./api .

RUN nest build

EXPOSE 8085