# --- ENVIRONMENT

FROM node:18.13.0 AS production

WORKDIR /urs/src/api      

COPY ./api/package*.json ./

RUN npm i --omit=dev --ignore-scripts

COPY ./api ./

COPY ./envs/.security.env ./api

# FIX BCRYPT BUG

RUN npm uninstall bcrypt
RUN npm install bcrypt
RUN npm run build