version: '3.8'

services:
  api:
    container_name: teste-api
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/Dockerfile.api
      target: production
    command: npm run start:debug
    restart: always
    env_file:
      - ../envs/.production.env
    volumes:
      - ../api:/usr/src/api
      - /usr/src/api/node_modules
    networks:
      - teste-network
    ports:
      - 8085:8085
      - 8229:8229
    depends_on:
      - db
      - redis

  db:
    container_name: db
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/postgres/Dockerfile.postgres
    restart: always
    env_file:
      - ../envs/.production.env
    networks:
      - teste-network
    ports:
      - 8432:8432
    volumes:
      - teste-db-data:/var/lib/postgresql/data
    command: 
      - "-p 8432"
  
  redis:
    container_name: redis
    image: redis:6.0.9
    restart: always
    networks:
      - teste-network
    ports:
      - 6379:6379

networks:
  teste-network:
    name: teste-network
    driver: bridge

volumes:
  teste-db-data:
    name: teste-db-data

